/*
 * This file is generated by jOOQ.
 */
package com.getbridge.homework.db;


import com.getbridge.homework.db.tables.FlywaySchemaHistory;
import com.getbridge.homework.db.tables.OneOnOnes;
import com.getbridge.homework.db.tables.Participants;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.one_on_ones</code>.
     */
    public final OneOnOnes ONE_ON_ONES = OneOnOnes.ONE_ON_ONES;

    /**
     * The table <code>public.participants</code>.
     */
    public final Participants PARTICIPANTS = Participants.PARTICIPANTS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            OneOnOnes.ONE_ON_ONES,
            Participants.PARTICIPANTS
        );
    }
}
