/*
 * This file is generated by jOOQ.
 */
package com.getbridge.homework.db;


import com.getbridge.homework.db.tables.FlywaySchemaHistory;
import com.getbridge.homework.db.tables.OneOnOnes;
import com.getbridge.homework.db.tables.Participants;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.one_on_ones</code>.
     */
    public static final OneOnOnes ONE_ON_ONES = OneOnOnes.ONE_ON_ONES;

    /**
     * The table <code>public.participants</code>.
     */
    public static final Participants PARTICIPANTS = Participants.PARTICIPANTS;
}
